version: "3.8"
services:
  app:
    container_name: lms_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public  
    depends_on:
      - mysql
    networks:
      - app_network

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
    - ./public:/usr/src/app/public
    ports:
      - 8100:80
    depends_on:
      - app
    environment:
      NGINX_FPM_HOST: app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  mysql:
    container_name: mysql
    image: mysql:8.0.20
    restart: always
    volumes:
      - lms-mysql:/var/lib/mysql
    ports:
      - 3316:3306
    environment:
      MYSQL_DATABASE: LMS
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
    networks:
      - app_network

  # redis:
  #   container_name: redis
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - app_network

networks:
  app_network:
    driver: bridge

volumes:
  lms-mysql:   